title: "IEEE-AizuStd"
markdown: kramdown
highighter: pygments
permalink: date
google_analytics_code: UA-52343779-3
url: http://ieee-aizustd.github.com
exclude:
- bin
- Gemfile
- Gemfile.lock
- Rakefile
- README.markdown
- vendor